title: Thesis Project
logo: /images/Picture1.png
description: This work was co-funded by the European Union under the programme of social cohesion “THALIA 2021-2027”, through Research and Innovation Foundation (Project: CONCEPT/0722/0031)
#show_downloads: true
theme: jekyll-theme-minimal 
